const REFERENCES=[{name:"Thabo M. - Tlhabane",date:"12 Jul 2026",text:"SafeJob showed SCAM - asked R200. Saved my taxi. Legit.",status:"Saved"},{name:"Keabetswe L. - Boitekong",date:"28 Jun 2026",text:"Checked security job. App said SAFE. Interview was real, didn't get job but app proved legit.",status:"Interview - Real"},{name:"Onalenna S. - Lethabong",date:"03 Aug 2026",text:"Gmail only job - SafeJob flagged it. Called company, no job. Qaphela!",status:"Verified fake"}];
function createUser(){const n=document.getElementById('fullName').value.trim(),p=document.getElementById('pin').value.trim();if(!n||!p){alert('Enter Name and PIN');return}localStorage.setItem('sj_name',n);localStorage.setItem('sj_pin',p);alert('User created! Login now');}
function login(){const n=document.getElementById('fullName').value.trim(),p=document.getElementById('pin').value.trim(),sn=localStorage.getItem('sj_name'),sp=localStorage.getItem('sj_pin');if(!sn){alert('Create User first');return}if(n!==sn||p!==sp){alert('Wrong Name or PIN');return}document.getElementById('login-page').classList.add('hidden');document.getElementById('dashboard').classList.remove('hidden');document.getElementById('welcome-msg').innerText=n+' - Verified';document.getElementById('greeting').innerText='Qaphela, '+n;loadStories();showReports();loadChecks();loadFeedback();}
function logout(){document.getElementById('dashboard').classList.add('hidden');document.getElementById('login-page').classList.remove('hidden');}
function forgotPin(){const sp=localStorage.getItem('sj_pin');alert(sp?'Hint: '+sp[0]+'***':'No user saved');}
function showTab(name,btn){document.querySelectorAll('[id^="tab-"]').forEach(e=>e.classList.add('hidden'));document.getElementById('tab-'+name).classList.remove('hidden');document.querySelectorAll('.tab').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active');}
function loadStories(){const d=document.getElementById('storiesList');d.innerHTML=REFERENCES.map(r=>`<div class="card" style="margin:8px 0;padding:14px"><b style="font-size:13px">${r.name}</b><br><small style="color:#6b7280">${r.date}</small><p style="font-size:13px;margin:8px 0;line-height:1.5">${r.text}</p><span class="status-tag">${r.status}</span></div>`).join('');}
function checkJob(){const t=document.getElementById('jobInput').value.toLowerCase(),res=document.getElementById('result');if(!t){res.innerText='Paste advert first';return}let s=0,r=[];if(t.includes('pay')||t.includes('fee')||t.includes('r200')||t.includes('r150')){s+=3;r.push('Requests payment')}if(t.includes('whatsapp')&&!t.includes('co.za')){s+=2;r.push('WhatsApp only')}if(t.includes('gmail.com')){s+=1;r.push('Gmail email')}if(s>=3){res.className='result-box scam';res.innerHTML='<b style="font-weight:800">HIGH RISK</b><br><br>'+r.join(', ')+'<br><br>Do not pay. Verify at Dept of Labour.'}else if(s>=1){res.className='result-box';res.innerHTML='<b style="font-weight:700">BE CAREFUL</b><br><br>'+r.join(', ')+'<br><br>Ask for company address.'}else{res.className='result-box safe';res.innerHTML='<b style="font-weight:700">LOOKS SAFER</b><br><br>No common scam signs found. Still verify address.'}}
function saveCheck(){const ids=['c1','c2','c3','c4'];const data={};ids.forEach(id=>data[id]=document.getElementById(id).checked);localStorage.setItem('sj_checks',JSON.stringify(data));updateProgress();}
function loadChecks(){const data=JSON.parse(localStorage.getItem('sj_checks')||'{}');Object.keys(data).forEach(k=>{if(document.getElementById(k))document.getElementById(k).checked=data[k]});updateProgress();const s=JSON.parse(localStorage.getItem('sj_safety')||'{}');['s1','s2','s3','s4','s5'].forEach(k=>{if(document.getElementById(k))document.getElementById(k).checked=s[k]||false});}
function updateProgress(){const ids=['c1','c2','c3','c4'];let c=ids.filter(id=>document.getElementById(id)?.checked).length;document.getElementById('checkProgress').innerText=c+'/4 checked - '+(c===4?'Ready to go for interview':'Complete all checks first');}
function saveSafety(){const ids=['s1','s2','s3','s4','s5'];const d={};ids.forEach(id=>d[id]=document.getElementById(id).checked);localStorage.setItem('sj_safety',JSON.stringify(d));}
function reportScam(){const l=document.getElementById('reportLink').value.trim();if(!l){alert('Paste number');return}let r=JSON.parse(localStorage.getItem('sj_reports')||'[]');r.push({text:l,date:new Date().toLocaleDateString()});localStorage.setItem('sj_reports',JSON.stringify(r));document.getElementById('reportLink').value='';showReports();}
function showReports(){let r=JSON.parse(localStorage.getItem('sj_reports')||'[]');const d=document.getElementById('reportList');if(d)d.innerHTML=r.map(x=>`<div style="padding:8px 0;border-bottom:1px solid #f3f4f6;font-size:12px"><b>${x.text}</b><br><small style="color:#6b7280">${x.date}</small></div>`).join('');}
function sendFeedback(){const t=document.getElementById('feedbackInput').value.trim();if(!t){alert('Type feedback');return}let f=JSON.parse(localStorage.getItem('sj_feedback')||'[]');f.push({text:t,date:new Date().toLocaleDateString()});localStorage.setItem('sj_feedback',JSON.stringify(f));document.getElementById('feedbackInput').value='';loadFeedback();}
function loadFeedback(){let f=JSON.parse(localStorage.getItem('sj_feedback')||'[]');const d=document.getElementById('feedbackList');if(d)d.innerHTML=f.map(x=>`<div style="padding:8px 0;border-bottom:1px solid #f3f4f6;font-size:12px">${x.text}<br><small style="color:#6b7280">${x.date}</small></div>`).join('');}
